# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cz123/Downloads/cn-cbor-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cz123/Downloads/cn-cbor-master/build

# Include any dependencies generated for this target.
include src/CMakeFiles/cn-cbor.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include src/CMakeFiles/cn-cbor.dir/compiler_depend.make

# Include the progress variables for this target.
include src/CMakeFiles/cn-cbor.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/cn-cbor.dir/flags.make

src/CMakeFiles/cn-cbor.dir/cn-cbor.c.o: src/CMakeFiles/cn-cbor.dir/flags.make
src/CMakeFiles/cn-cbor.dir/cn-cbor.c.o: ../src/cn-cbor.c
src/CMakeFiles/cn-cbor.dir/cn-cbor.c.o: src/CMakeFiles/cn-cbor.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cz123/Downloads/cn-cbor-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object src/CMakeFiles/cn-cbor.dir/cn-cbor.c.o"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT src/CMakeFiles/cn-cbor.dir/cn-cbor.c.o -MF CMakeFiles/cn-cbor.dir/cn-cbor.c.o.d -o CMakeFiles/cn-cbor.dir/cn-cbor.c.o -c /home/cz123/Downloads/cn-cbor-master/src/cn-cbor.c

src/CMakeFiles/cn-cbor.dir/cn-cbor.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/cn-cbor.dir/cn-cbor.c.i"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/cz123/Downloads/cn-cbor-master/src/cn-cbor.c > CMakeFiles/cn-cbor.dir/cn-cbor.c.i

src/CMakeFiles/cn-cbor.dir/cn-cbor.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/cn-cbor.dir/cn-cbor.c.s"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/cz123/Downloads/cn-cbor-master/src/cn-cbor.c -o CMakeFiles/cn-cbor.dir/cn-cbor.c.s

src/CMakeFiles/cn-cbor.dir/cn-create.c.o: src/CMakeFiles/cn-cbor.dir/flags.make
src/CMakeFiles/cn-cbor.dir/cn-create.c.o: ../src/cn-create.c
src/CMakeFiles/cn-cbor.dir/cn-create.c.o: src/CMakeFiles/cn-cbor.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cz123/Downloads/cn-cbor-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object src/CMakeFiles/cn-cbor.dir/cn-create.c.o"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT src/CMakeFiles/cn-cbor.dir/cn-create.c.o -MF CMakeFiles/cn-cbor.dir/cn-create.c.o.d -o CMakeFiles/cn-cbor.dir/cn-create.c.o -c /home/cz123/Downloads/cn-cbor-master/src/cn-create.c

src/CMakeFiles/cn-cbor.dir/cn-create.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/cn-cbor.dir/cn-create.c.i"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/cz123/Downloads/cn-cbor-master/src/cn-create.c > CMakeFiles/cn-cbor.dir/cn-create.c.i

src/CMakeFiles/cn-cbor.dir/cn-create.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/cn-cbor.dir/cn-create.c.s"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/cz123/Downloads/cn-cbor-master/src/cn-create.c -o CMakeFiles/cn-cbor.dir/cn-create.c.s

src/CMakeFiles/cn-cbor.dir/cn-encoder.c.o: src/CMakeFiles/cn-cbor.dir/flags.make
src/CMakeFiles/cn-cbor.dir/cn-encoder.c.o: ../src/cn-encoder.c
src/CMakeFiles/cn-cbor.dir/cn-encoder.c.o: src/CMakeFiles/cn-cbor.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cz123/Downloads/cn-cbor-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building C object src/CMakeFiles/cn-cbor.dir/cn-encoder.c.o"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT src/CMakeFiles/cn-cbor.dir/cn-encoder.c.o -MF CMakeFiles/cn-cbor.dir/cn-encoder.c.o.d -o CMakeFiles/cn-cbor.dir/cn-encoder.c.o -c /home/cz123/Downloads/cn-cbor-master/src/cn-encoder.c

src/CMakeFiles/cn-cbor.dir/cn-encoder.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/cn-cbor.dir/cn-encoder.c.i"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/cz123/Downloads/cn-cbor-master/src/cn-encoder.c > CMakeFiles/cn-cbor.dir/cn-encoder.c.i

src/CMakeFiles/cn-cbor.dir/cn-encoder.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/cn-cbor.dir/cn-encoder.c.s"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/cz123/Downloads/cn-cbor-master/src/cn-encoder.c -o CMakeFiles/cn-cbor.dir/cn-encoder.c.s

src/CMakeFiles/cn-cbor.dir/cn-error.c.o: src/CMakeFiles/cn-cbor.dir/flags.make
src/CMakeFiles/cn-cbor.dir/cn-error.c.o: ../src/cn-error.c
src/CMakeFiles/cn-cbor.dir/cn-error.c.o: src/CMakeFiles/cn-cbor.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cz123/Downloads/cn-cbor-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object src/CMakeFiles/cn-cbor.dir/cn-error.c.o"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT src/CMakeFiles/cn-cbor.dir/cn-error.c.o -MF CMakeFiles/cn-cbor.dir/cn-error.c.o.d -o CMakeFiles/cn-cbor.dir/cn-error.c.o -c /home/cz123/Downloads/cn-cbor-master/src/cn-error.c

src/CMakeFiles/cn-cbor.dir/cn-error.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/cn-cbor.dir/cn-error.c.i"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/cz123/Downloads/cn-cbor-master/src/cn-error.c > CMakeFiles/cn-cbor.dir/cn-error.c.i

src/CMakeFiles/cn-cbor.dir/cn-error.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/cn-cbor.dir/cn-error.c.s"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/cz123/Downloads/cn-cbor-master/src/cn-error.c -o CMakeFiles/cn-cbor.dir/cn-error.c.s

src/CMakeFiles/cn-cbor.dir/cn-get.c.o: src/CMakeFiles/cn-cbor.dir/flags.make
src/CMakeFiles/cn-cbor.dir/cn-get.c.o: ../src/cn-get.c
src/CMakeFiles/cn-cbor.dir/cn-get.c.o: src/CMakeFiles/cn-cbor.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cz123/Downloads/cn-cbor-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object src/CMakeFiles/cn-cbor.dir/cn-get.c.o"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT src/CMakeFiles/cn-cbor.dir/cn-get.c.o -MF CMakeFiles/cn-cbor.dir/cn-get.c.o.d -o CMakeFiles/cn-cbor.dir/cn-get.c.o -c /home/cz123/Downloads/cn-cbor-master/src/cn-get.c

src/CMakeFiles/cn-cbor.dir/cn-get.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/cn-cbor.dir/cn-get.c.i"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/cz123/Downloads/cn-cbor-master/src/cn-get.c > CMakeFiles/cn-cbor.dir/cn-get.c.i

src/CMakeFiles/cn-cbor.dir/cn-get.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/cn-cbor.dir/cn-get.c.s"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && /usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/cz123/Downloads/cn-cbor-master/src/cn-get.c -o CMakeFiles/cn-cbor.dir/cn-get.c.s

# Object files for target cn-cbor
cn__cbor_OBJECTS = \
"CMakeFiles/cn-cbor.dir/cn-cbor.c.o" \
"CMakeFiles/cn-cbor.dir/cn-create.c.o" \
"CMakeFiles/cn-cbor.dir/cn-encoder.c.o" \
"CMakeFiles/cn-cbor.dir/cn-error.c.o" \
"CMakeFiles/cn-cbor.dir/cn-get.c.o"

# External object files for target cn-cbor
cn__cbor_EXTERNAL_OBJECTS =

dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/cn-cbor.c.o
dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/cn-create.c.o
dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/cn-encoder.c.o
dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/cn-error.c.o
dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/cn-get.c.o
dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/build.make
dist/lib/libcn-cbor.so: src/CMakeFiles/cn-cbor.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/cz123/Downloads/cn-cbor-master/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Linking C shared library ../dist/lib/libcn-cbor.so"
	cd /home/cz123/Downloads/cn-cbor-master/build/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/cn-cbor.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/cn-cbor.dir/build: dist/lib/libcn-cbor.so
.PHONY : src/CMakeFiles/cn-cbor.dir/build

src/CMakeFiles/cn-cbor.dir/clean:
	cd /home/cz123/Downloads/cn-cbor-master/build/src && $(CMAKE_COMMAND) -P CMakeFiles/cn-cbor.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/cn-cbor.dir/clean

src/CMakeFiles/cn-cbor.dir/depend:
	cd /home/cz123/Downloads/cn-cbor-master/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/cz123/Downloads/cn-cbor-master /home/cz123/Downloads/cn-cbor-master/src /home/cz123/Downloads/cn-cbor-master/build /home/cz123/Downloads/cn-cbor-master/build/src /home/cz123/Downloads/cn-cbor-master/build/src/CMakeFiles/cn-cbor.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/cn-cbor.dir/depend

