# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# compile C with /usr/bin/cc
C_DEFINES = -Dcn_cbor_EXPORTS

C_INCLUDES = -I/home/cz123/Downloads/cn-cbor-master/src/../include -I/home/cz123/Downloads/cn-cbor-master/src/../src

C_FLAGS =  -g -O0 -fprofile-arcs -ftest-coverage -g -fPIC   -std=gnu99 -Wall -Wextra -pedantic -Werror

